version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
# version: "3"

# services:
#   postgres:
#     container_name: postgres
#     image: postgres:latest
#     ports:
#     - "5432:5432"
#     env_file:
#     - docker.env
#     networks:
#     - exodus
 
#   # pgadmin:
#   #   links:
#   #   - postgres:postgres
#   #   container_name: pgadmin
#   #   image: dpage/pgadmin4
#   #   ports:
#   #   - "8080:80"
#   #   volumes:
#   #   - /data/pgadmin:/root/.pgadmin
#   #   env_file:
#   #   - docker.env
#   #   networks:
#   #   - exodus
 
# networks:
#   exodus:
#     driver: bridge